Added Ethereum DApps in Motion
jasonwalsh/awesome-dapps pull request #7
Opened 2018-12-25 20:22 UTC by roziunicorn

Hello,
would you please add this video?

Thanks

2018-12-26 21:18 UTC, jasonwalsh requested changes
Hey @roziunicorn just some minor changes and then I will merge. Thanks!

2018-12-26 21:18 UTC, jasonwalsh commented on readme.md
> +- [Ethereum DApps in Motion](https://www.manning.com/livevideo/ethereum-dapps-in-motion) Julien Klepatch teaches you how to build DApps using the Ethereum toolchain and an emerging body of best pract
Remove the trailing whitespace.

2018-12-26 21:18 UTC, jasonwalsh commented on readme.md
> +- [Videos](#Videos)
Change this line:

```diff
- [Videos](#Videos)
+ [Videos](#videos)
```

2018-12-31 08:30 UTC, roziunicorn commented
Thank you so much:) and Happy New Year!

2018-12-31 19:20 UTC, jasonwalsh commented
@roziunicorn this isn't resolved. You still need to make the changes I requested for me to accept the PR.

2019-01-04 20:36 UTC, roziunicorn commented
Sorry, just did it!

2020-01-22 19:31 UTC, closed without merging